dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    version: 0.8.1
    remappings: 
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"